django-projects/ircious/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ircious.django_openidconsumer.views',
    (r'^openid/$', 'begin', {'sreg': 'email'}),
    (r'^openid/complete/$', 'complete'),
    (r'^openid/signout/$', 'signout'),
)

urlpatterns += patterns('',
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'', include('ircious.ircious_app.urls')),
)

django-projects/ircious/ircious_app/models.py
from django.db import models, connection

# Create your models here.
class LinkObj(models.Model):
    url = models.URLField(max_length=300)
    title = models.CharField(max_length=200)
    slug = models.SlugField(prepopulate_from=("title",))
    last_post = models.ForeignKey('LinkPost', blank=True, null=True)
    screenshot = models.URLField(blank=True, null=True)
    class Admin:
        pass
    def __unicode__(self): return self.title
    def toplist(self, numobjects):
        fieldlist = ['url', 'title', 'slug']
        long_fieldlist = map((lambda x: 'ircious_app_linkobj.'+x), fieldlist)
        cursor = connection.cursor()
        cursor.execute("SELECT "+ ", ".join(long_fieldlist) + ", COUNT(ircious_app_linkpost.link_id) AS num FROM ircious_app_linkobj INNER JOIN ircious_app_linkpost ON ircious_app_linkobj.id = ircious_app_linkpost.link_id GROUP BY ircious_app_linkobj.id ORDER BY num DESC LIMIT %i" % numobjects)
        result = cursor.fetchall()
        fieldlist += ['num']
        return map((lambda x: dict(zip(fieldlist, x))), result)
    class Meta:
        ordering = ['-last_post']
        get_latest_by = "last_post_id"
                    

class User(models.Model):
    oid_url = models.URLField(max_length=200, blank=True)
    email = models.EmailField(blank=True)
    favlinks = models.ManyToManyField(LinkObj, null=True, blank=True)
    class Admin:
        pass
    def toplist(self, numobjects):
        cursor = connection.cursor()
        cursor.execute("SELECT ircious_app_nick.nickname, COUNT(ircious_app_linkpost.user_id) AS num FROM ircious_app_user INNER JOIN ircious_app_nick ON ircious_app_nick.user_id = ircious_app_user.id INNER JOIN ircious_app_linkpost ON ircious_app_user.id = ircious_app_linkpost.user_id GROUP BY ircious_app_user.id ORDER BY num DESC LIMIT %i" % numobjects)
        result = cursor.fetchall()
        fieldlist = ['nick', 'num']
        return map((lambda x: dict(zip(fieldlist, x))), result)
    def __unicode__(self):
        return (self.oid_url) or ("User %i" % self.id)

class IrcNetwork(models.Model):
    name = models.CharField(max_length=30)
    uri = models.CharField(max_length=200, blank=True)
    bot_nick = models.CharField(max_length=30, default="ircious")
    def __unicode__(self): return self.name
    class Admin:
        pass

class IrcChannel(models.Model):
    name = models.CharField(max_length=30, core=True)
    network = models.ForeignKey(IrcNetwork, edit_inline=models.STACKED, num_in_admin=3)
    active = models.BooleanField(default=False)
    requested_by = models.ForeignKey(User)
    def __unicode__(self): return self.name
    class Admin:
        pass
    def toplist(self, numobjects):
        cursor = connection.cursor()
        cursor.execute("SELECT ircious_app_ircchannel.name, ircious_app_ircnetwork.uri, COUNT(ircious_app_linkpost.channel_id) AS num FROM ircious_app_ircchannel INNER JOIN ircious_app_ircnetwork ON ircious_app_ircchannel.network_id = ircious_app_ircnetwork.id LEFT JOIN ircious_app_linkpost ON ircious_app_ircchannel.id = ircious_app_linkpost.channel_id WHERE active = 1 GROUP BY ircious_app_ircchannel.id ORDER BY num DESC LIMIT %i" % numobjects)
        result = cursor.fetchall()
        fieldlist = ['name', 'network_uri','num']
        return map((lambda x: dict(zip(fieldlist, x))), result)


class LinkPost(models.Model):
    link = models.ForeignKey(LinkObj)
    user = models.ForeignKey(User)
    comment = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    channel = models.ForeignKey(IrcChannel)
    class Admin:
        pass
    class Meta:
        ordering = ['-date']
        get_latest_by = "date"
    def __unicode__(self): return self.comment

class Nick(models.Model):
    nickname = models.CharField(max_length=30, core=True)
    user = models.ForeignKey(User, edit_inline=models.STACKED, num_in_admin=1)
    verified_user = models.BooleanField(default=False)
    class Admin:
        pass

django-projects/ircious/templates/base.html
{% load misc %}<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sv" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<head>
    <title>Ircious - {% block title %}Start{% endblock %}</title>
    <link rel="alternate" type="application/atom+xml" href="http://ircious.flukkost.nu/{% if channel %}channel/{{ channel }}/{% endif %}{% if nick %}user/{{ nick.nickname }}/{% endif %}{% if object.slug %}slug/{{ object.slug }}/{% endif %}feed/{{ page }}"/>
    <link rel="stylesheet" type="text/css" href="http://media.ircious.flukkost.nu/style.css"/>
    <script src="http://media.ircious.flukkost.nu/localize_dates.js" type="text/javascript"/>
    <script src="http://media.ircious.flukkost.nu/favscript.js" type="text/javascript"/>
    {% block headers %}{% endblock %}
</head>
<body>
    <div id="header">
        <h1><a href="/">Ircious</a></h1>
        <h2>Your favourite links, straight from IRC</h2>
        <div id="login-info">
        {% if openid %}
            Welcome, {{ openid.nick_set.get.nickname }}. <a href="/openid/signout">Logout</a>
        {% else %}
            <form action="/openid/" method="post">
                <p>
                    <label for="openid_url">Sign in:</label>
                    <input class="openid" type="text" name="openid_url" id="openid_url"/>
                    <a href="/accounts/">Help</a>
                </p>
            </form>
        {% endif %}
        <div class="clear"/>
        </div>
    </div>
    <div id="content">
        <div id="innercontent">
            {% if error %}<div id="error">{{ error }}</div>{% endif %}
            {% block content %}<p>Nice weather for ducks</p>{% endblock %}
            {% if prev or page %}
            <p class="prev"><a href="http://ircious.flukkost.nu/{% if channel %}channel/{{ channel }}/{% endif %}{% if nick %}user/{{ nick.nickname }}/{% endif %}{% if object.slug %}slug/{{ object.slug }}/{% endif %}{{ prev }}">Previous</a></p>
            {% endif %}
            {% if next %}
            <p class="next"><a href="http://ircious.flukkost.nu/{% if channel %}channel/{{ channel }}/{% endif %}{% if nick %}user/{{ nick.nickname }}/{% endif %}{% if object.slug %}slug/{{ object.slug }}/{% endif %}{{ next }}">Next</a></p>
            {% endif %}
        </div>
    </div>
    <div id="sidebar">
        <ul class="xoxo">
            <li>
                <h3>Most popular</h3>
                <ul>
                {% for pop in popular %}
                    <li><a href="/slug/{{ pop.slug }}">{{ pop.title|striptags }}</a> ({{ pop.num }})</li>
                {% endfor %}
                </ul>
            </li>
            <li>
                <h3>Users</h3>
                <ul>
                {% for nick in topusers %}
                    <li><a href="/user/{{ nick.nick }}">{{ nick.nick }}</a> ({{ nick.num }})</li>
                {% endfor %}
                </ul>
            </li>
            <li>
                <h3>Channels</h3>
                <ul>
                {% for channel in topchannels %}
                    <li><a href="/channel/{{ channel.name|strip:"#" }}">{{ channel.name }}</a> {% if channel.num %}({{ channel.num }}){% endif %}</li>
                {% endfor %}
                </ul>
                <p><a href="/add_channel/">Request another channel</a></p>
            </li>
            <li>
                <a href="http://ircious.flukkost.nu/{% if channel %}channel/{{ channel }}/{% endif %}{% if nick %}user/{{ nick.nickname }}/{% endif %}{% if object.slug %}slug/{{ object.slug }}/{% endif %}feed/{{ page }}" rel="alternate" type="application/atom+xml"><img src="http://media.ircious.flukkost.nu/feed-icon.png" alt="Feed"/></a>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
    <div id="footer">
        Copyright &#169; 2007 <a href="http://flukkost.nu/blog/about-me">Robin Sonefors</a>. No rights reserved. <a href="/whatisthis">What is this?</a>

    </div>
</body>
</html>